package ro.ophthacloud.shared.audit;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.Map;
import java.util.UUID;

/**
 * JPA entity for the {@code audit_log} table.
 * <p>
 * Audit records are <strong>immutable</strong> once persisted — the PostgreSQL trigger
 * {@code trg_audit_log_immutable} prevents any UPDATE or DELETE.
 * This entity is therefore write-once; there are no {@code @LastModifiedDate} or
 * {@code @Version} columns (audit log does not extend {@code BaseEntity}).
 * <p>
 * Created exclusively through {@link AuditLogService#log(AuditEntry)}.
 * Never mutated after persistence.
 *
 * @see AuditEntry
 * @see AuditLogService
 */
@Entity
@Table(name = "audit_log")
@Getter
@Setter
@NoArgsConstructor
public class AuditLogEntity {

    /** Primary key — generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    /**
     * The tenant that owns this audit record.
     * References {@code tenants(id)} — cascades on tenant deletion.
     */
    @Column(name = "tenant_id", nullable = false, updatable = false)
    private UUID tenantId;

    /**
     * Keycloak user UUID (the {@code sub} claim) as a string.
     * Denormalized intentionally — audit records must survive user deletion.
     */
    @Column(name = "actor_id", nullable = false, updatable = false, length = 256)
    private String actorId;

    /**
     * Action performed.
     * Canonical values: {@code CREATE}, {@code UPDATE}, {@code DELETE},
     * {@code SIGN}, {@code EXPORT}, {@code VIEW}.
     */
    @Column(name = "action", nullable = false, updatable = false, length = 64)
    private String action;

    /**
     * Simple class name of the audited entity (e.g. {@code "Patient"}, {@code "Consultation"}).
     */
    @Column(name = "entity_type", nullable = false, updatable = false, length = 128)
    private String entityType;

    /**
     * Primary key of the audited entity. Nullable for bulk/list operations.
     */
    @Column(name = "entity_id", updatable = false)
    private UUID entityId;

    /**
     * Field-level change diff stored as JSONB.
     * Structure: {@code {"fieldName": {"old": "...", "new": "..."}}}.
     * Null for {@code DELETE} and {@code VIEW} actions.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "changed_fields", updatable = false, columnDefinition = "jsonb")
    private Map<String, Object> changedFields;

    /**
     * Client IP address. Extracted from {@code X-Forwarded-For} header with fallback
     * to {@code HttpServletRequest.getRemoteAddr()} by {@code RequestContextHelper}.
     */
    @Column(name = "ip_address", updatable = false, length = 64)
    private String ipAddress;

    /**
     * Timestamp of the audit event. Set by PostgreSQL {@code DEFAULT NOW()};
     * also set by the application before insert for consistency.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Pre-persist hook: ensure createdAt is populated if not already set. */
    @PrePersist
    void onPrePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }
}
