package ro.ophthacloud.infrastructure.persistence;

import jakarta.persistence.*;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.UUID;

/**
 * Base class for all JPA entities in OphthaCloud.
 * <p>
 * Provides:
 * <ul>
 *   <li>{@code id} — UUID primary key, auto-generated by Hibernate (matches {@code gen_random_uuid()} in PostgreSQL)</li>
 *   <li>{@code createdAt} — set once on insert, never updated</li>
 *   <li>{@code updatedAt} — updated on every merge</li>
 *   <li>{@code version} — optimistic locking via {@link Version}</li>
 * </ul>
 * All subclasses must NOT add their own {@code @Id} field.
 */
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(of = {"id"})
public abstract class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @Version
    @Column(name = "version")
    private Long version;
}
